##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "DSCI350: Medieval Womens Medicine" 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: "A collection of manuscripts and objects pertaining to womens health in the middle ages."
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "This collection explores the practices and practitioners of women’s medicine in the medieval era. I believe this topic is important for the history of women’s health and wellness and to examine how women were treated in the medieval medical sphere. This collection contains works from popular schools of medicine in the medieval period, one written by a woman and the others by men.  The aim of this collection is to compile content pertaining to women’s health which can be studied to better understand contemporary medical practices. My intended audience would be those studying medicine or women and gender studies. From this collection one could find medical practices that were used in the medieval period and how that translates to current medical practices. One thing I wish to document is any malpractice that evolved in the medical field. How much of women’s medicine today was influenced by medical misconceptions in the past?"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: CollectionBuilder

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: medicine-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
